services:
  clinic:
    build: .
    container_name: clinic-app
    command: npm run dev -- -H 0.0.0.0 -p 8888
    env_file:
      - .env
    ports:
      - "8888:8888"
    volumes:
      - ./:/app
      - /app/node_modules
    restart: unless-stopped
